const API_URL = import.meta.env.VITE_API_URL;

export const AlumnosTable = `${API_URL}/estudiantes`;
export const PersonalTable = `${API_URL}/personal`;
export const AsignacionesTable = `${API_URL}/asignacion`;
export const GruposTable = `${API_URL}/grupos`;
export const MisAlumnosTable = `${API_URL}/docente/mis-alumnos`;
export const AsignacionGrupoTable = `${API_URL}/asignacion-grupo`;
export const QuizzesTable = `${API_URL}/quizzes`;
export const ActividadesTable = `${API_URL}/actividades`;
export const AlumnoMisGruposTable = `${API_URL}/alumno/mis-grupos`;
export const AlumnoActividadesTable = `${API_URL}/alumno/actividades`;
export const CalificacionesTable = `${API_URL}/calificaciones`;
export const AlumnoCalificacionesTable = `${API_URL}/alumno/mis-calificaciones`;
export const ReporteCalificacionesTable = `${API_URL}/calificaciones/reporte`;
export const EstadisticasTable = `${API_URL}/dashboard/estadisticas`;
export const GeneradorIATable = `${API_URL}/ia/generar`;
export const AuthTable = `${API_URL}/auth`;
export const AlumnoTodasLasActividadesTable = `${API_URL}/alumno/mis-actividades`;